AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.

Resources:
  lexdisambiguate:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lex_disambiguate.lambda_handler
      Runtime: python3.7
      CodeUri: ./
      Description: ''
      MemorySize: 512
      Timeout: 20
      Policies:
        - 'AmazonLexFullAccess'
        - 'AWSLambdaBasicExecutionRole'
      Layers:
        - 'arn:aws:lambda:us-east-1:113088814899:layer:Klayers-python37-spacy:26'
        - 'arn:aws:lambda:us-east-1:041132386971:layer:en_core_web_smv2:1'
