AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.

Resources:
  searchphoto:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./
      Description: ''
      MemorySize: 512
      Timeout: 20
      Role: 'arn:aws:iam::041132386971:role/service-role/search_photo-role-laeady0s'
      Layers:
        - 'arn:aws:lambda:us-east-1:113088814899:layer:Klayers-python37-spacy:26'
        - 'arn:aws:lambda:us-east-1:041132386971:layer:en_core_web_smv2:1'

  uploadphoto:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::041132386971:role/service-role/upload_photo-role-2brby1w5'
      Events:
        uploadphoto:
          Type: Api
          Properties:
            Path: /upload
            Method: PUT
